Added deb file creation

diff --git a/pkgntd b/pkgntd
--- a/pkgntd
+++ b/pkgntd
@@ -9,74 +9,148 @@ COL_BLUE=$ESC_SEQ"34;01m"
 COL_MAGENTA=$ESC_SEQ"35;01m"
 COL_CYAN=$ESC_SEQ"36;01m"
 
-which dch > /dev/null
-if [ 0 != "$?" ]; then
-    echo -e "${COL_RED}dch not installed, cannot proceed${COL_RESET}"
+set -e
+
+USAGE="$0 /path/to/drupal version"
+
+DRUPAL_ROOT=$1
+VERSION=$2
+
+if [ -z "$DRUPAL_ROOT" ]; then
+    echo $USAGE
+    echo You must specify the path to the drupal root folder
     exit 1
 fi
 
-PACKAGE_NAME='testdr-1.0.1'
-VERSION=1.0.1
-DRUPAL_ROOT=/home/tobias/workspace/Cottaging/DrupalMake/testdr-1.0.1
-DESCRIPTION="Airhead clown fudge monkeyfighting"
-
-mkdir -p $DRUPAL_ROOT/debian
-CWD=`pwd`
-cd $DRUPAL_ROOT
-
-if [ ! -f $DRUPAL_ROOT/debian/changelog ]; then
-    dch --create -v $VERSION --package $PACKAGE_NAME 
+if [ -z "$VERSION" ]; then
+    echo $USAGE
+    echo You must specify a version number
+    exit 1
 fi
 
-echo "9" > $DRUPAL_ROOT/debian/compat
+PACKAGE_NAME=`basename $DRUPAL_ROOT`
 
-cat >$DRUPAL_ROOT/debian/control<<EOF
-Source: $PACKAGE_NAME
-Maintainer: Toby Batch <tobias@neontribe.co.uk>
-Section: misc
-Priority: optional
-Standards-Version: 3.9.5
-Build-Depends: debhelper (>= 9)
+if [ ! -d "$DRUPAL_ROOT/sites/default/sql" ]; then
+    chmod 755 ${DRUPAL_ROOT}/sites/default
+    mkdir -p ${DRUPAL_ROOT}/sites/default/sql
+    chmod 555 ${DRUPAL_ROOT}/sites/default
+    APACHE_VERSION=`apache2ctl -v|head -n 1|cut -c 24-26`
+    if [ "$APACHE_VERSION" == "2.4" ]; then
+        cat >${DRUPAL_ROOT}/sites/default/sql/.htaccess<<EOF
+Require all denied
+EOF
+    elif [ "$APACHE_VERSION" == "2.2" ]; then
+        cat >${DRUPAL_ROOT}/sites/default/sql/.htaccess<<EOF
+Order deny,allow
+Deny from all
+EOF
+    else
+        echo -e "${COL_RED}Unable to determine apache version.  I can create a .htaccess file in"
+        echo -e "${DRUPAL_ROOT}/sites/default/sql/.htaccess.  You will need to create this yourself"
+        echo -e "and re-run this script.${COL_RESET}"
+    fi
 
-Package: $PACKAGE_NAME
-Architecture: any
-Depends: libapache2-mod-php5 | libapache2-mod-php5filter | php5-cgi | php5-fpm | php5, php5-mysql | php5-mysqli | php5-mysqlnd, php5-mcrypt, php5-json, debconf (>= 0.5) | debconf-2.0, dbconfig-common, php-gettext, ucf (>= 0.28)
-Recommends: apache2 | lighttpd | httpd, php5-gd, mysql-client
-Suggests: mysql-server
-Description: greet user
- $DESCRIPTION
+fi
+
+drush -r $DRUPAL_ROOT sql-dump --ordered-dump --result-file=sites/default/sql/site.sql  --structure-tables-key=common
+
+mkdir -p $PACKAGE_NAME/$PACKAGE_NAME-$VERSION
+# cp -r $DRUPAL_ROOT $PACKAGE_NAME/$PACKAGE_NAME-$VERSION
+# tar & gzip the site.  the packager can't handle .info files
+CWD=`pwd`
+cd $DRUPAL_ROOT
+tar -zcf ${CWD}/${PACKAGE_NAME}/${PACKAGE_NAME}-${VERSION}/${PACKAGE_NAME}.tgz * .htaccess
+cd -
+
+cd $PACKAGE_NAME/$PACKAGE_NAME-$VERSION
+dh_make -c GPL -e ${PACKAGE_NAME}${VERSION}@neontribe.co.uk -n -s -i -y 
+
+rm debian/*.{ex,EX}
+
+cat >debian/install<<EOF
+${PACKAGE_NAME}.tgz /var/www/html/${PACKAGE_NAME}-${VERSION}
 EOF
 
-cat >$DRUPAL_ROOT/debian/copyright<<EOF
-This package was debianized by Norbert Tretkowski <nobse@debian.org> on
-Thu, 29 May 2003 14:43:17 +0200.
+user=`echo ${PACKAGE_NAME} | cut -c 1-4`
+user=$user`echo ${VERSION}| sed -e "s/\./_/g"`
 
-It was downloaded from http://www.apsis.ch/pound/
+cat >debian/postinst<<EOF
+#!/bin/bash
 
-Upstream Author: Robert Segall <roseg@apsis.ch>
+case "\$1" in
+    configure)
+        tar -C /var/www/html/${PACKAGE_NAME}-${VERSION} -zxf /var/www/html/${PACKAGE_NAME}-${VERSION}/${PACKAGE_NAME}.tgz
+        # get root password
+        echo "Enter the root password for your MySQL instance:"
+        stty -echo
+        read mysqlroot
+        stty echo
 
-Copyright (C) 2002-2007 Apsis GmbH
+        # drop user and db if exists
+        mysql -u root -p\$mysqlroot -h localhost -s -e "GRANT USAGE ON *.* TO $user@localhost;"
+        mysql -u root -p\$mysqlroot -h localhost -s -e "DROP USER $user@localhost;"
+        mysql -u root -p\$mysqlroot -h localhost -s -e "DROP DATABASE IF EXISTS $user ;"
 
-Pound is free software; you can redistribute it and/or modify
-it under the terms of the GNU General Public License as published by
-the Free Software Foundation; either version 3 of the License, or
-(at your option) any later version.
+        # create db and user
+        mysql -u root -p\$mysqlroot -h localhost -s -e "CREATE USER $user@localhost IDENTIFIED BY '$user';"
+        mysql -u root -p\$mysqlroot -h localhost -s -e "GRANT USAGE ON *.* TO $user@localhost IDENTIFIED BY '$user' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;"
+        mysql -u root -p\$mysqlroot -h localhost -s -e "CREATE DATABASE IF NOT EXISTS $user ;"
+        mysql -u root -p\$mysqlroot -h localhost -s -e "GRANT ALL PRIVILEGES ON $user.* TO $user@localhost;"
 
-Pound is distributed under the GPL with the additional
-exemption that compiling, linking, and/or using OpenSSL is allowed.
+        # echo inport db
+        mysql -u root -p\$mysqlroot -h localhost $user < /var/www/html/${PACKAGE_NAME}-${VERSION}/sites/default/sql/site.sql
 
+        # update settings.php
+        chmod 666 /var/www/html/${PACKAGE_NAME}-${VERSION}/sites/default/settings.php
+        chmod 777 /var/www/html/${PACKAGE_NAME}-${VERSION}/sites/default
+        sed -i "s/      'database' => .*/      'database' => '$user',/g" /var/www/html/${PACKAGE_NAME}-${VERSION}/sites/default/settings.php
+        sed -i "s/      'username' => .*/      'username' => '$user',/g" /var/www/html/${PACKAGE_NAME}-${VERSION}/sites/default/settings.php
+        sed -i "s/      'password' => .*/      'password' => '$user',/g" /var/www/html/${PACKAGE_NAME}-${VERSION}/sites/default/settings.php
+        chmod 444 /var/www/html/${PACKAGE_NAME}-${VERSION}/sites/default/settings.php
+        chmod 555 /var/www/html/${PACKAGE_NAME}-${VERSION}/sites/default
 
-The GPLv3 is located at /usr/share/common-licenses/GPL-3 on your Debian
-system.
+        echo "<VirtualHost *:80>" > /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-24
+        echo "  ServerAdmin webmaster@localhost" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-24
+        echo "  DocumentRoot /var/www/html/${PACKAGE_NAME}-${VERSION}" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-24
+        echo "  ErrorLog \${APACHE_LOG_DIR}/error.log" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-24
+        echo "  CustomLog \${APACHE_LOG_DIR}/access.log combined" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-24
+        echo "  <Directory /var/www/html/${PACKAGE_NAME}-${VERSION}>" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-24
+        echo "    AllowOverride All" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-24
+        echo "  </Directory>" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-24
+        echo "</VirtualHost>" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-24
+
+        echo "<VirtualHost *:80>" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22
+        echo "  ServerAdmin webmaster@localhost" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22
+        echo "  DocumentRoot /var/www/html/${PACKAGE_NAME}-${VERSION}" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22
+        echo "  <Directory />" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22
+        echo "    Options FollowSymLinks" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22
+        echo "    AllowOverride None" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22
+        echo "  </Directory>" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22
+        echo "  <Directory /var/www/html/${PACKAGE_NAME}-${VERSION}>" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22
+        echo "    Options Indexes FollowSymLinks MultiViews" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22
+        echo "    AllowOverride All" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22
+        echo "    Order allow,deny" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22
+        echo "    allow from all" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22
+        echo "  </Directory>" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22
+        echo "  ErrorLog \${APACHE_LOG_DIR}/error.log" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22
+        echo "  LogLevel warn" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22
+        echo "  CustomLog \${APACHE_LOG_DIR}/access.log combined" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22
+        echo "</VirtualHost>" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument" >&2
+        exit 1
+    ;;
+esac
+
+#DEBHELPER#
+
+exit 0
 EOF
 
-cat >$DRUPAL_ROOT/debian/rules<<EOF
-#!/usr/bin/make -f
-%:
-	dh \$@
-EOF
-
-mkdir -p $DRUPAL_ROOT/debian/source
-echo "3.0 (quilt)" > -p $DRUPAL_ROOT/debian/source/format
-
-debuild -us -uc
+cd - && cd $PACKAGE_NAME/$PACKAGE_NAME-$VERSION
+debuild -b -i -us -uc
